<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Display Driver Uninstaller</AssemblyName>
    <RootNamespace></RootNamespace>
    <ApplicationIcon>DDU.ico</ApplicationIcon>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>On</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <NoWarn>$(NoWarn);WPF0001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Windows" />
    <Import Include="System.Windows.Controls" />
    <Import Include="System.Windows.Data" />
    <Import Include="System.Windows.Documents" />
    <Import Include="System.Windows.Input" />
    <Import Include="System.Windows.Shapes" />
    <Import Include="System.Windows.Media" />
    <Import Include="System.Windows.Media.Imaging" />
    <Import Include="System.Windows.Navigation" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="English.xml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\amd_logo.png" />
    <Resource Include="Resources\nvidia_logo.png" />
    <Resource Include="Resources\btn_donate_LG.gif" />
    <Resource Include="Resources\DDU.ico" />
    <Resource Include="Resources\ddu_logo.png" />
    <Resource Include="Resources\btn_partner.png" />
    <Resource Include="Resources\become_a_patron_button.png" />
    <Resource Include="Resources\realtek-logo.PNG" />
    <Resource Include="Resources\creative_logo.png" />
    <Resource Include="Resources\intel_logo.jpg" />
    <Resource Include="Resources\discord@2x.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
